import jwt from "jsonwebtoken"

//                            (req, res)
export const generateToken = (userId, res)=>{
    const token = jwt.sign({userId}, process.env.JWT_SECRET, {
        expiresIn:"7d"
    });

    res.cookie("jwt", token, {
        maxAge: 7*24*60*60*1000, //time in ms
        httpOnly: true, //prevent XSS attacks cross-site scripting attacks, basically make secure
        sameSite: "strict", //CSRF attacks crooss-site request forgery attacks, again for making more secure 
        secure: process.env.NODE_ENV !== "development" //this is going to be true if we r in production,i.e "secure" will determine if it is http or https site, s in https stands for secure 
    });

    return token;
}



//token structure: header.payload.signature , e.g: xxx.yyyyyy.zzz
//payload we give to make token prefered to be unique, payload can be object
//const token = jwt.sign(payload, secretKey, options); header is automatically generated by JWT, option is a obj like payload